name: conference_app
description: "Conference management Flutter application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.5.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.0.0

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.7.2

  # UI utilities
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  intl: ^0.19.0

  # Cloudinary (file uploads)
  cloudinary_public: ^0.23.1

  # Image picker
  image_picker: ^1.0.4

  # File handling
  dio: ^5.4.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:21 or higher

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Guest/Pahune/
    - assets/images/organizers/
    - assets/FinalIconss/
    - assets/PartnerLogo/ConferencePartners/
    - assets/PartnerLogo/AssociationPartners/
    - assets/PartnerLogo/TechnicalCoPartners/
    - assets/ProgramSchedule/
    - assets/Developer/
