import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';
import 'dart:developer' as dev;

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  Stream<User?> get user => _auth.authStateChanges();

  Future<void> submitSignupRequest({
    required String name,
    required String email,
    required String role,
    required String password,
    String? paperTitle,
  }) async {
    try {
      dev.log('AuthService: Creating Auth account for $email');
      
      // 1. Create Firebase Auth User
      UserCredential credential = await _auth.createUserWithEmailAndPassword(
        email: email, 
        password: password
      );

      // 2. Create User Document in Firestore with 'pending' status
      UserModel newUser = UserModel(
        uid: credential.user!.uid,
        userId: '', // Will be generated by admin on approval
        role: role,
        status: 'pending',
        name: name,
        email: email,
        paperTitle: paperTitle,
        createdAt: DateTime.now(),
        profileComplete: false,
      );

      await _firestore.collection('users').doc(credential.user!.uid).set(newUser.toMap());
      
      // 3. Create a separate Signup Request for Admin convenience
      await _firestore.collection('signup_requests').doc(credential.user!.uid).set({
        'uid': credential.user!.uid,
        'name': name,
        'email': email,
        'role': role,
        'paperTitle': paperTitle,
        'status': 'pending',
        'createdAt': FieldValue.serverTimestamp(),
      });

      // 4. Sign out immediately (user must be approved to log in)
      await _auth.signOut();
      
      dev.log('AuthService: Signup request submitted successfully.');
    } on FirebaseAuthException catch (e) {
      if (e.code == 'email-already-in-use') {
        throw Exception('This email is already registered.');
      }
      rethrow;
    } catch (e) {
      dev.log('AuthService Error: $e');
      rethrow;
    }
  }

  Future<UserCredential?> login(String email, String password) async {
    try {
      dev.log('AuthService: Attempting login for $email');
      UserCredential credential = await _auth.signInWithEmailAndPassword(email: email, password: password);

      DocumentSnapshot userDoc = await _firestore.collection('users').doc(credential.user!.uid).get();
      
      if (!userDoc.exists) {
        await _auth.signOut();
        throw Exception('User record not found.');
      }

      UserModel user = UserModel.fromMap(userDoc.data() as Map<String, dynamic>, userDoc.id);

      if (user.status == 'pending') {
        await _auth.signOut();
        throw Exception('Your account is pending admin approval.');
      } else if (user.status == 'rejected') {
        await _auth.signOut();
        throw Exception('Your account request was rejected. Please contact support.');
      }

      return credential;
    } catch (e) {
      dev.log('AuthService Login Error: $e');
      rethrow;
    }
  }

  Future<void> logout() async {
    await _auth.signOut();
  }

  Future<UserModel?> getCurrentUserModel() async {
    User? user = _auth.currentUser;
    if (user != null) {
      // Force fetch from server to avoid stale data from local cache
      DocumentSnapshot doc = await _firestore.collection('users').doc(user.uid).get(const GetOptions(source: Source.server));
      if (doc.exists) {
        return UserModel.fromMap(doc.data() as Map<String, dynamic>, doc.id);
      }
    }
    return null;
  }

  Future<void> completeProfile(String uid, Map<String, dynamic> profileData) async {
    await _firestore.collection('users').doc(uid).update({
      ...profileData,
      'profileComplete': true,
    });
  }
}
