// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFU2vfP9D9YCsgRG8zoFjEbBd1I1aHTCY',
    appId: '1:589462914987:web:d1756fd61c83a31bfd74ee',
    messagingSenderId: '589462914987',
    projectId: 'ic-smart-conferenceapp',
    authDomain: 'ic-smart-conferenceapp.firebaseapp.com',
    storageBucket: 'ic-smart-conferenceapp.firebasestorage.app',
    measurementId: 'G-R5LVP59JRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_F5anppUd3VCG9BeJc2Aseytqdz_JNE',
    appId: '1:589462914987:android:859c890c71f49662fd74ee',
    messagingSenderId: '589462914987',
    projectId: 'ic-smart-conferenceapp',
    storageBucket: 'ic-smart-conferenceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFaovy3knA0jX7ZAPa5-S-oTq7ybet9iM',
    appId: '1:589462914987:ios:49fdd9da66a08dc0fd74ee',
    messagingSenderId: '589462914987',
    projectId: 'ic-smart-conferenceapp',
    storageBucket: 'ic-smart-conferenceapp.firebasestorage.app',
    iosBundleId: 'com.example.conferenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFaovy3knA0jX7ZAPa5-S-oTq7ybet9iM',
    appId: '1:589462914987:ios:49fdd9da66a08dc0fd74ee',
    messagingSenderId: '589462914987',
    projectId: 'ic-smart-conferenceapp',
    storageBucket: 'ic-smart-conferenceapp.firebasestorage.app',
    iosBundleId: 'com.example.conferenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFU2vfP9D9YCsgRG8zoFjEbBd1I1aHTCY',
    appId: '1:589462914987:web:bc3b7d12bc560f26fd74ee',
    messagingSenderId: '589462914987',
    projectId: 'ic-smart-conferenceapp',
    authDomain: 'ic-smart-conferenceapp.firebaseapp.com',
    storageBucket: 'ic-smart-conferenceapp.firebasestorage.app',
    measurementId: 'G-G0TT686EWB',
  );

}